name: Temporary workflow to check if the notifications are working as expected

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - ci-*

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  DIFFUSERS_IS_CI: yes
  HF_HOME: /mnt/cache
  OMP_NUM_THREADS: 8
  MKL_NUM_THREADS: 8
  PYTEST_TIMEOUT: 600
  RUN_SLOW: yes
  RUN_NIGHTLY: yes

jobs:
  run_nightly_tests:
    name: Run a nightly test
    strategy:
      fail-fast: false
    runs-on: docker-gpu
    container:
      image: diffusers/diffusers-pytorch-cuda
      options: --shm-size "16gb" --ipc host -v /mnt/hf_cache:/mnt/cache/ --gpus 0
    steps:
      - name: Checkout diffusers
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Install dependencies
        run: |
          python -m pip install -e .[quality,test]
          python -m pip install -U git+https://github.com/huggingface/transformers
          python -m pip install git+https://github.com/huggingface/accelerate
          pip install pytest-reportlog
      - name: Run a nightly PyTorch CUDA test
        run: |
            python -m pytest -n 1 --max-worker-restart=0 --dist=loadfile \
              --report-log=single_nightly_test.log \
              tests/lora/test_lora_layers_peft.py::StableDiffusionLoRATests::test_integration_logits_no_scale
      - name: Generate Report and Notify Channel
        if: always()
        run: |
          pip install slack_sdk tabulate
          python scripts/log_reports.py >> $GITHUB_STEP_SUMMARY